### ISSUE TITLE
Cannot read property 'hasPermission' of null

### ISSUE THREAD

**Issue by daishitie** [Michael-J-Scofield/discord-anti-spam#102] opened 2020-06-02 06:55 UTC
TypeError: Cannot read property 'hasPermission' of null
    at C:\Users\Manny\Documents\MCPZ\Watchdog\watchdog\node_modules\discord-anti-spam\index.js:162:64
    at Array.some (<anonymous>)
    at AntiSpam.message (C:\Users\Manny\Documents\MCPZ\Watchdog\watchdog\node_modules\discord-anti-spam\index.js:162:30)
    at Client.<anonymous> (C:\Users\Manny\Documents\MCPZ\Watchdog\watchdog\main.js:47:12)
    at Client.emit (events.js:315:20)
    at MessageCreateAction.handle (C:\Users\Manny\Documents\MCPZ\Watchdog\watchdog\node_modules\discord.js\src\client\actions\MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (C:\Users\Manny\Documents\MCPZ\Watchdog\watchdog\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (C:\Users\Manny\Documents\MCPZ\Watchdog\watchdog\node_modules\discord.js\src\client\websocket\WebSocketManager.js:386:31)
    at WebSocketShard.onPacket (C:\Users\Manny\Documents\MCPZ\Watchdog\watchdog\node_modules\discord.js\src\client\websocket\WebSocketShard.js:436:22)
    at WebSocketShard.onMessage (C:\Users\Manny\Documents\MCPZ\Watchdog\watchdog\node_modules\discord.js\src\client\websocket\WebSocketShard.js:293:10)tShard.js:293:10)                                                                                                                      function without a catch
(node:2916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an asynce the CLI flag `--unhandle function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejectionshandled will terminate the_mode). (rejection id: 1)
(node:2916) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not
handled will terminate the Node.js process with a non-zero exit code.

**Comment by Scraayp** [comment] 2020-07-21 17:41
* exemptPermissions​

**Comment by Party78** [comment] 2020-11-08 16:44
i got this error too help

**Comment by Scraayp** [comment] 2020-11-08 16:45
What did you put in the exemptPermissions ​option?

**Comment by Party78** [comment] 2020-11-08 17:51
if (!message.member.hasPermission("ADMINISTRATOR"))  return;

**Comment by Party78** [comment] 2020-11-08 17:52
const Discord = require("discord.js");
const client = new Discord.Client();
var prefix = "+";

client.on("message", message => {

if (message.content.startsWith(prefix + "dm")) {
if (!message.member.hasPermission("ADMINISTRATOR"))  return;
let args = message.content.split(" ").slice(1);
var argresult = args.join(' '); 
  message.guild.members.filter(m => m.presence.status !== 'ignore').forEach(m => {
 m.send(`${argresult}\n ${m}`);
})
 message.channel.send(`\`${message.guild.members.filter(m => m.presence.status !== 'online').size}\` **MESSAGE SENT** `); 
 message.delete(); 
};     
});

**Comment by Scraayp** [comment] 2020-11-08 17:56
That is not a error on our side

**Comment by Scraayp** [comment] 2020-11-08 17:56
Its your own command

**Comment by SkiloZZ** [comment] 2020-11-15 22:28
I also had the same problem so I changed the version of discord.js and it worked.

**Comment by Scraayp** [comment] 2020-11-17 08:35
The issue is: 
The antispam does get broken when it detects spam of bot when its set to ignore bots! 

I will be working on a resolution....

**Comment by Scraayp** [comment] 2020-11-17 08:41
Issue has been fixed in the development branch!

**Closed** 2020-11-17 08:46 UTC
